controller_manager:
    ros__parameters:
        update_rate: 100  # Hz
        use_sim_time: true

    joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

    position_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

position_trajectory_controller:
    ros__parameters:
        joints:
            - fl_hip_roll
            - fl_hip_pitch
            - fl_knee_joint

    command_interfaces:
        - position

    state_interfaces:
        - position
        - velocity
